### ISSUE TITLE
[Bug] delux button missing

### ISSUE THREAD

**Issue by TilCreator** [Nukesor/sticker-finder#33]
Recreate:
- Add sticker packs and tag stickers (probably not necessary)
- (accidentally) enter command `/delete_history`
- Send bot Sticker
Expected:
- "Tag as deluxe" button still appearing
Actually behaviour:
- "Tag as deluxe" button not appearing anymore

Sry because of the many issues, the project is awesome and I really like it.
If I can find the time I will try to fixing my issues myself.

**Comment by Nukesor** [comment]
Try `/help` once. The issue should be fixed by now.

**Comment by TilCreator** [comment]
Did that, the deluxe button is still missing.
![Screenshot_20190928_161444](https://user-images.githubusercontent.com/18621411/65817730-179a0c00-e20b-11e9-873a-92a38429eac3.png)

**Comment by TilCreator** [comment]
Oh, sorry, it is fixed, I was just confused...

**Comment by Nukesor** [comment]
Ahh :D.
That was actually a bug from before ;D.
Deluxe is actually a global flag, that should only be displayed to admins. This has been fixed recently

**Comment by TilCreator** [comment]
I thought at first that it is user specific, but now I get it ^^

**Comment by TilCreator** [comment]
![Screenshot_20190928_161844](https://user-images.githubusercontent.com/18621411/65817788-a60e8d80-e20b-11e9-80c4-ab805f2f17ad.png)
It still gets displayed on these messages thou.

**Comment by Nukesor** [comment]
Fml. Found the bug. I'll fix it soon. Thanks for bringing this up to my attention :D

The `deluxe` sticker packs are quite worthless right now, since all users tagged sticker packs as deluxe as they liked. Completely unregulated.

**Comment by TilCreator** [comment]
fixed
